### PR TITLE
GPII-3497: Temporary fix for express-pouchdb data corruption and cleanup issues.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-3497](https://issues.gpii.net/browse/GPII-3497) for details.

### CODE REVIEW

**Comment by amb26** [comment]
This would be a great place to piggy-back the updates for https://issues.gpii.net/browse/GPII-3569 - otherwise, looks good to me

**Comment by the-t-in-rtf** [comment]
@amb26, I have updated all dependencies and linting.  There are still high impact vulnerabilities, which I can't address without updating the forked libraries themselves.  Also, although my strategy resolves the problems we saw in CI, the cleanup of temporary content isn't working in Windows (permission errors are thrown).  I can either focus on updating and further modifying whatever bit it is that's blocking cleanup, or I can work on converting universal to use the new couchdb test harness.   I will spend a short amount of time attempting a further workaround for express-pouchdb.  If no temporary solution is apparent, IMO we should:

1.  Add a note about the issues to the README
2. Work on adapting universal to use the new test harness.

**Comment by amb26** [comment]
Looking good - could we also have an update of pouchdb-auth to address the final moderate? :
````
npm ls base64url

gpii-pouchdb@1.0.13 C:\gpii-pouchdb
`-- @the-t-in-rtf/express-pouchdb@4.0.0-dev.20181210T193931Z.19be373
  `-- pouchdb-auth@4.0.0
    +-- base64url@1.0.6
    `-- couchdb-calculate-session-id@1.1.3
      `-- base64url@3.0.1

  Moderate        Out-of-bounds Read
  Package         base64url
  Dependency of   @the-t-in-rtf/express-pouchdb
  Path            @the-t-in-rtf/express-pouchdb > pouchdb-auth > base64url
  More info       https://nodesecurity.io/advisories/658
````

**Comment by the-t-in-rtf** [comment]
I can try updating the dependency and running their tests, then cutting a dev release and using it in the tests in gpii-pouchdb.  My suspicion is that we'll get away with it, we don't use their auth much anyway.

**Comment by the-t-in-rtf** [comment]
OK, @amb26, as we discussed in chats, this turned out to be the work of an hour, and is done.  It does suggest that we should actually review [the pouchdb-server pull](https://github.com/the-t-in-rtf/pouchdb-server/pull/1) just so another human understands the publishing workflow.

**Pull request merged**
