### PR TITLE
GPII-2397: Clean up express-pouchdb log file after test runs....

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-2397](https://issues.gpii.net/browse/GPII-2397) for details.

### CODE REVIEW

**Comment by amb26** [comment]
Widespread failure in the case the log file is not present:

```
17:30:05.478:  FATAL ERROR: Uncaught exception: EPERM: operation not permitted, open 'C:\Users\Bosmon\AppData\Local\Temp\log.txt'
Error: EPERM: operation not permitted, open 'C:\Users\Bosmon\AppData\Local\Temp\log.txt'
    at Error (native)
17:30:05.480:  Current activity:
17:30:05.481:  jq: FAIL: Module "Testing persistence within a single restart..." Test name "Confirm that we have indexed records after adding one..." - Message:
 Unexpected failure in test case (see following log for more details): EPERM: operation not permitted, open 'C:\Users\Bosmon\AppData\Local\Temp\log.txt'
17:30:05.482:  jq: Source:     at kettle.test.handleUncaughtException (E:\source\gits\gpii-pouchdb\node_modules\kettle\lib\test\KettleTestUtils.js:31:15)
    at Object.fire (E:\source\gits\gpii-pouchdb\node_modules\infusion\src\framework\core\js\Fluid.js:1533:40)
    at process.onUncaughtException (E:\source\gits\gpii-pouchdb\node_modules\infusion\src\module\fluid.js:101:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:296:26)
17:30:05.485:  This database already has one or more records, no data will be loaded...
17:30:05.486:  Data loaded for database '_replicator'...
17:30:05.487:  This database already has one or more records, no data will be loaded...
17:30:05.487:  Data loaded for database 'persistence'...
17:30:05.488:  This database already has one or more records, no data will be loaded...
17:30:05.489:  Data loaded for database 'pouch__all_dbs__'...
17:30:05.497:  Sending a GET request to: /persistence/_design/persistence/_view/byId?startKey=%22new%22 on port 6798
17:30:05.540:  jq: Test concluded - Module "Testing persistence within a single restart..." Test name "Confirm that we have indexed records after adding one..."
: 2/3 passed - FAIL
```

**Comment by the-t-in-rtf** [comment]
I was able to reproduce this locally.  The latest error was the result of a long-running goof where I created log files one directory too high, something like `/tmp/log.txt` instead of `/tmp/{component_id}/log.txt`.  Addressing this fixed everything but the persistence tests, which all run against the same directory.  I ended up adding a function to ensure the log file name is also unique.

As part of investigating this, I discovered that all the required express-pouchdb options can now be configured directly using options passed when instantiating express-pouchdb.  Previously, I had to save the options to a file and then pass options to load that file.  I removed this workaround, which will reduce the amount of cleanup required as well.

@amb26, this is ready for review again.

**Comment by the-t-in-rtf** [comment]
The docs have been updated as well.  I caught a few previously added options/features this go around.

**Comment by cindyli** [comment]
The commits so far in the pull request help to solve the "out of memory" issue I encountered when using gpii-pouchdb version 1.0.1 as a node dependency for [my universal data loader pull request](https://github.com/GPII/universal/pull/503).

In case someone is interested, [here](https://botbot.me/freenode/fluid-work/2017-04-27/?msg=84808701&page=1) is the detail about the "out of memory" issue.

**Comment by amb26** [comment]
The cleanup issues are again much improved and I think acceptable. The detritus left behind in /tmp in my system is now the following:
```
-rwx------+ 1 Bosmon None 838067 May  1 15:47 46C1.tmp
-rwx------+ 1 Bosmon None  25927 May  1 15:47 4C9C.tmp
-rwx------+ 1 Bosmon None  25909 May  1 15:47 4ECE.tmp
-rwx------+ 1 Bosmon None  26850 May  1 15:47 4EEE.tmp
drwx------+ 1 Bosmon None      0 May  1 15:47 scoped_dir_10928_24872
```

The "tmp" files seem to be pure binary, perhaps created by a browser process. The directory remains empty after running the pure node-based process

**Comment by the-t-in-rtf** [comment]
I have created [GPII-2400](https://issues.gpii.net/browse/GPII-2400) to track the remaining cleanup work in gpii-testem.

**Pull request merged**
